name: runComment
on:
  issue_comment:
    types: [created]
  # workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    # uses: github-actions/pipelines/.github/workflows/deploy-ansible-adhoc.yml@v1
    
    steps: 
      - name: Run Print
        if: startsWith(github.event.comment.body, '/runTest')
        run: |
          echo "Hello World"
          echo "🍏 This job's status is ${{ job.status }}."
    # secrets: inherit
    # with:
    #   app: ramboplans
    #   aws-env: qa7a